## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
# your code
arr = np.random.randint(10, size=10)
result = np.where((arr<=8)&(arr>3),(-1)*arr,arr)

print(arr)
print(result)

[4 3 8 1 2 3 0 2 0 8]
[-4  3 -8  1  2  3  0  2  0 -8]


**2.** Заменить максимальный элемент случайного массива на 0

In [3]:
# your code
arr = np.random.randint(10, size=10)
result = np.where(arr == np.amax(arr),0,arr)

print(arr)
print('')
print(result)

[1 9 4 6 4 4 4 9 1 4]

[1 0 4 6 4 4 4 0 1 4]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [4]:
# your code
arr = np.random.randint(5, size=(2,3))
result = np.transpose([np.tile(arr[0],len(arr[0])), np.repeat(arr[1],len(arr[0]))])

print(arr)
print('')
print(result)

[[4 3 3]
 [3 1 4]]

[[4 3]
 [3 3]
 [3 3]
 [4 1]
 [3 1]
 [3 1]
 [4 4]
 [3 4]
 [3 4]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [5]:
# your code
A = np.random.randint(5, size=(8,3))
B = np.random.randint(5, size=(2,2))
mask = [np.isin(B, x).all() for x in A]
result = A[mask]

print(A)
print('')
print(B)
print('')
print(result)



[[2 0 2]
 [1 1 4]
 [0 2 1]
 [4 0 3]
 [3 3 0]
 [4 2 4]
 [1 0 2]
 [0 4 0]]

[[0 2]
 [3 4]]

[]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [6]:
# your code
arr = np.random.randint(3, size=(10,3))
mask = [any(x!=x[0]) for x in arr]
result = arr[mask]

print(arr)
print('')
print(result)

[[0 0 2]
 [1 1 2]
 [2 1 2]
 [0 1 0]
 [0 2 2]
 [1 0 1]
 [0 2 1]
 [2 0 2]
 [0 0 0]
 [1 0 1]]

[[0 0 2]
 [1 1 2]
 [2 1 2]
 [0 1 0]
 [0 2 2]
 [1 0 1]
 [0 2 1]
 [2 0 2]
 [1 0 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [7]:
# your code
arr = np.random.randint(3, size=(10,3))
result = np.unique(arr, axis=0)

print(arr)
print('')
print(result)

[[2 1 1]
 [0 1 2]
 [1 1 1]
 [0 1 2]
 [0 0 2]
 [0 1 2]
 [1 2 0]
 [2 1 1]
 [0 1 0]
 [0 1 0]]

[[0 0 2]
 [0 1 0]
 [0 1 2]
 [1 1 1]
 [1 2 0]
 [2 1 1]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [8]:
# your code
#numpy
x = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
result = np.prod(np.diag(x), where=np.diag(x)>0)
print(result)


#list
x = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
result = 1
for i in range(len(x) if len(x)<len(x[0]) else len(x[0])):
    result *=x[i][i] if x[i][i]!=0 else 1
print(result)



3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [9]:
# your code
#numpy
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
result = np.array_equal(np.sort(x),np.sort(y))
print(result)

#list
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
result = sorted(x)==sorted(y)
print(result)

True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [10]:
# your code
#numpy
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zeroes = np.where(x[:-2]==0)    # find zeroes indexes not evaluating last element
max_value = np.amax(x[zeroes[0]+1])    #find values that goes after zero by adding 1 to indexes
print(max_value)


#list
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
max_value = 0
for i in range(len(x)-1):
    if x[i]==0 and x[i+1]>max_value:
        max_value = x[i+1]
print(max_value)

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [11]:
# your code
#numpy
x = np.array([2, 2, 2, 3, 3, 3, 5])
result = np.unique(x, return_counts=True)
print(result)

#list
x = [2, 2, 2, 3, 3, 3, 5]
unique_x = set(x)
count_x = []
for i in unique_x:
    count_x.append(x.count(i))
print(list(unique_x),count_x)

(array([2, 3, 5]), array([3, 3, 1], dtype=int64))
[2, 3, 5] [3, 3, 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [12]:
# your code
# initial data
from scipy.spatial.distance import cdist
from math import sqrt
from time import perf_counter

# initial data
X = np.random.randint(10, size=(10, 4))
Y = np.random.randint(10, size=(10, 4))
X_list = X.tolist()
Y_list = Y.tolist()

# timer decorator
def timer(fn):
    def inner(*args, **kwargs):
        start = perf_counter()
        result = fn(*args, **kwargs)
        end = perf_counter()
        elapsed = end - start
        print(elapsed)
        return result
    return inner

#n numpy function
@timer
def numpy_dist(arr1,arr2):
    P = np.add.outer(np.sum(arr1**2, axis=1), np.sum(arr2**2, axis=1))
    N = np.dot(arr1, arr2.T)
    return np.sqrt(P - 2*N)

print(numpy_dist(X,Y))
print('')

# simple python function
@timer
def python_dist(arr1,arr2):
    dist = []
    for i in range(len(arr1)):
        inner_dist = []
        for j in range(len(arr2)):
            coord_sum = 0
            for k in range(len(arr1[0])):
                coord_sum += (arr1[i][k]-arr2[j][k])**2
            inner_dist.append(sqrt(coord_sum))
        dist.append(inner_dist)
    return dist

print(python_dist(X_list,Y_list))
print('')

# scipy function
@timer
def scipy_dist(arr1,arr2):
    return cdist(arr1,arr2,'euclidean')

print(scipy_dist(X,Y))


0.00017799999841372482
[[ 6.55743852 12.76714533 10.29563014  4.89897949  9.48683298  7.61577311
   5.83095189  3.16227766  8.66025404  5.38516481]
 [ 8.54400375 11.          8.36660027  8.83176087  6.92820323  3.16227766
   4.69041576  8.24621125  1.73205081  7.41619849]
 [10.34408043  8.42614977  8.83176087 11.5758369   8.24621125  7.87400787
  10.29563014 12.64911064  7.54983444 12.52996409]
 [10.34408043  6.40312424  3.16227766  8.60232527  5.09901951 10.48808848
   7.87400787  7.07106781 11.18033989  8.06225775]
 [11.83215957  6.164414    2.64575131 10.53565375  4.58257569 10.63014581
   8.66025404  9.32737905 11.04536102  9.59166305]
 [11.22497216  3.46410162  5.19615242 11.70469991  7.68114575 11.
  10.14889157 11.35781669 10.29563014 11.04536102]
 [ 7.61577311  4.69041576  4.12310563  7.54983444  6.70820393  9.11043358
   6.70820393  6.244998    8.71779789  6.4807407 ]
 [11.22497216  5.47722558  3.87298335 11.26942767  6.55743852  9.8488578
   7.93725393  9.8488578   8.71779789

_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [13]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [14]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [15]:
# your code
average_calories = np.average(calorie_stats)
print(average_calories)

106.88311688311688


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [16]:
# your code
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [17]:
# your code
median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [18]:
# your code
nth_percentile = 4
percentile = np.percentile(calorie_stats,nth_percentile)
print(percentile)

70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [19]:
# your code
more_calories = (calorie_stats>60).mean()*100
print(more_calories)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [20]:
# your code
calorie_std = np.std(calorie_stats)
print(calorie_std)

# Yes, we can assume that most flakes have an average of 100 cal.
# Our value of CrunchieMunchies is at 2 std from and average, and we can use it in promotion.

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [21]:
# your code

# Currently in the fitness industry, a lot of attention is paid to weight loss.
# Most people are of the opinion that in order to lose weight, you need to consume low-calorie foods.
# Due to the fact that our flakes have very low calories (much less then most of other products) we can use it as a main way to promote our product.